name: CI

on:
  push:
    branches-ignore:
      - "renovate/**"
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun run setup
      - run: bun run check
      - run: bun run test
